version: "2"
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 80:80
        links: 
            - php
        volumes:
            - .:/var/www/html
            - ./docker/conf:/etc/nginx/conf.d
        restart: always
        
    php:
        build: ./docker/
        container_name: php
        restart: always
        volumes:
            - .:/var/www/html
        links:
            - mysql
    mysql:
        image: mysql:5.7
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=pass
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        ports:
            - 3306:3306
        restart: always

    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8082:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        restart: always
        depends_on:
            - mysql